GOVORGAN = {
    'AU': 'Arbetsmarknadsutskottet',
    'CU': 'Civilutskottet',
    'FiU': 'Finansutskottet',
    'FöU': 'Försvarsutskottet',
    'JuU': 'Justitieutskottet',
    'KrU': 'Kulturutskottet',
    'KU': 'Konstitutionsutskottet',
    'MjU': 'Miljö- och jordbruksutskottet',
    'NU': 'Näringsutskottet',
    'SfU': 'Socialförsäkringsutskottet',
    'SkU': 'Skatteutskottet',
    'SoU': 'Socialutskottet',
    'TU': 'Trafikutskottet',
    'UbU': 'Utbildningsutskottet',
    'UU': 'Utrikesutskottet',
    'JuSoU': 'Sammansatta justitie- och socialutskottet',
    'KUU': 'Sammansatta konstitutions- och Utrikesutskottet',
    'UMJU': 'Sammansatta utrikes- och miljö- och jordbruksutskottet',
    'USoU': 'Sammansatta utrikes- och socialutskottet',
    'UFöU': 'Sammansatta utrikes- och försvarsutskottet',
    'BoU': 'Bostadsutskottet',
    'JoU': 'Jordbruksutskottet',
    'LU': 'Lagutskottet'
}